/* extra layer */
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

/* some size optimizations */
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_MUSIC_MODE

/* disable all default rgb effects */
#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON

#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS

#undef ENABLE_RGB_MATRIX_PIXEL_RAIN

#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE

#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE

#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef ENABLE_RGB_MATRIX_SPLASH

#undef ENABLE_RGB_MATRIX_SOLID_SPLASH

#undef RGB_MATRIX_KEYPRESSES

/* Default colors */

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE 48 // a very little bit acid yellow
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100 // limit maximum brightness to 100 out of 255

/* Fixes non-corrcet tuning for led driver, actually just reset to default */
#undef SNLED27351_CURRENT_TUNE
#define SNLED27351_CURRENT_TUNE \
        { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF }

// Enable QK_MAKE
#define ENABLE_COMPILE_KEYCODE
